[package]
name = "etheroit/replicaservice"
version = "1.0.2"
license = "Apache License 2.0"
authors = ["loleris"]
description = "loleris' ReplicaService (ReplicaService) forked for wally"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"