[package]
name = "etheroit/replicacontroller"
version = "1.0.0"
license = "Apache License 2.0"
authors = ["loleris"]
description = "loleris' ReplicaService (ReplicaController) forked for wally"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"